#+TITLE: RaSP: [R]esize [a]nd [S]plit Images for [P]rinting

* Introduction

RaSP is a simple python program which resizes images and splits them into
sections for printing on multiple sheets of paper and outputs a multi-page PDF
document.

* Usage

EXAMPLE: resize input image to 1000mm wide and split up for printing on multiple
sheets of A4 paper:

: python rasp.py -x 1000 image.png

Command Line Options:
- -h, --help       = print usage info and exit
- -x, --width      = target width in mm
- -y, --height     = target height in mm
- -p, --paper-size = paper size (a4|a3) (a4 is the default)
- -b, --border     = border size in mm (0 is the default)

All remaining args should be image filenames:
- RaSP currently recognises only ".png" and ".jpg" image files
- multiple image files can be given

The output is a multi-page PDF document. RaSP will create a sub-directory called
"temp_images", where the individual parts of the last sliced image are stored as
PNG files.

* Dependencies
- getopt
- img2pdf
- numpy
- PIL/Pillow

* Possible Issues

A couple of known bugs are described on the img2pdf PyPi page:
https://pypi.org/project/img2pdf/

Solutions are provided in both cases.

* See Also

This Python package seems to do a very similar job:
https://blog.whidev.com/split-image-tiles-python/
